name: apiverve_dogbreeds
description: Dog Breeds is a simple tool for getting information about dog breeds. It returns information such as breed name, temperament, lifespan, and more.
version: 1.1.14
homepage: https://apiverve.com/marketplace/dogbreeds?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/dogbreeds-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
