// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DogBreeds
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("breed")]
        public string Breed { get; set; }

        [JsonProperty("foundCount")]
        public long? FoundCount { get; set; }

        [JsonProperty("foundBreeds")]
        public FoundBreed[] FoundBreeds { get; set; }
    }

    public partial class FoundBreed
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("weight")]
        public Weight Weight { get; set; }

        [JsonProperty("height")]
        public Height Height { get; set; }

        [JsonProperty("bredFor")]
        public string BredFor { get; set; }

        [JsonProperty("group")]
        public string Group { get; set; }

        [JsonProperty("life_span")]
        public LifeSpan LifeSpan { get; set; }

        [JsonProperty("traits")]
        public string[] Traits { get; set; }
    }

    public partial class Height
    {
        [JsonProperty("lowerInches")]
        public long? LowerInches { get; set; }

        [JsonProperty("upperInches")]
        public long? UpperInches { get; set; }
    }

    public partial class LifeSpan
    {
        [JsonProperty("lowerYears")]
        public long? LowerYears { get; set; }

        [JsonProperty("upperYears")]
        public long? UpperYears { get; set; }
    }

    public partial class Weight
    {
        [JsonProperty("lowerLbs")]
        public long? LowerLbs { get; set; }

        [JsonProperty("upperLbs")]
        public long? UpperLbs { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
